import test from '/levels/test.tmx';
import level1 from '/levels/1level.tmx';
import level2 from '/levels/2level.tmx';
import level3 from '/levels/3level.tmx';
import level4 from '/levels/4level.tmx';
import level5 from '/levels/5level.tmx';
import level6 from '/levels/6level.tmx';
import level7 from '/levels/7level.tmx';
import level8 from '/levels/8level.tmx';
import level9 from '/levels/9level.tmx';
import level10 from '/levels/10level.tmx';
import level11 from '/levels/11level.tmx';
import level12 from '/levels/12level.tmx';
import level13 from '/levels/13level.tmx';
import level14 from '/levels/14level.tmx';
import level15 from '/levels/15level.tmx';
import level16 from '/levels/16level.tmx';

export const levels = [level1, level2, level3, level4, level5, level6, level7, level8, level9, level10, level11, level12, level13, level14, level15, level16];
export const eggs_levels = [test];
